server:
  port: 50052

database:
  host: localhost
  port: 5432
  user: postgres
  password: Primlab2020
  dbname: lolkek
  poolsize: 20

kafka:
  broker_list:
    - "localhost:9092"
  topic: "testtopic"
