server:
  port: 50053

database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: postgres
  poolsize: 20

kafka:
  broker_list:
    - "localhost:9092"
  topic: "testtopic"
